name: VoxelClock
main: com.thevoxelbox.voxelclock.VoxelClock
version: 1.1
commands:
  clock:
    description: Gives the player the current VoxelTime
    usage: /<command>
  whenis:
    description: Gives player current time based off a specified offset
    usage: /<command>